
scenario:
  start: '2022-02-01'
  end: '2022-02-28'

tech_colors:
  nuclear: "#549ca2"
  fossil: "#f6986b"
  biomass: "#dbc263"
  interconnector: "#dd75b0"
  onwind: "#7ac677"
  offwind: "#6895dd"
  solar: "#f9d002"
  hydro: "#0079c1"
  cascade: "#46caf0"
  PHS: "#4ca1d3"
  battery: "#ea581e"
  demand_flex: "magenta"

nice_names:
  nuclear: "Nuclear"
  fossil: "Natural Gas and Coal"
  biomass: "Biomass"
  interconnector: "Interconnector"
  onwind: "Onshore Wind"
  offwind: "Offshore Wind"
  solar: "Solar"
  hydro: "Hydropower"
  cascade: "Cascading Hydro"
  PHS: "Pumped Hydro Storage"
  battery: "Battery"
  demand_flex: "Flexible Demand"