
scenario:
  start: '2022-02-01'
  end: '2022-02-28'

tech_colors:
  onwind: "#7ac677"
  offwind: "#6895dd"
  hydro: "#0079c1"
  PHS: "#4ca1d3"
  biomass: "#dbc263"
  fossil: "#f6986b"
  nuclear: "#549ca2"
  interconnector: "#dd75b0"
  cascade: "#46caf0"
  solar: "#f9d002"
  battery: "#ace37f"
  demand_flex: "magenta"

nice_names:
  onwind: "Onshore Wind"
  offwind: "Offshore Wind"
  hydro: "Hydropower"
  cascade: "Cascading Hydro"
  PHS: "Pumped Hydro Storage"
  biomass: "Biomass"
  fossil: "Natural Gas and Coal"
  nuclear: "Nuclear"
  interconnector: "Interconnector"
  solar: "Solar"
  battery: "Battery"
  demand_flex: "Flexible Demand"