carrier_colors:
  onwind: "#7ac677"
  offwind: "#6895dd"
  hydro: "#0079c1"
  PHS: "#4ca1d3"
  coal: "#454546"
  biomass: "#dbc263"
  fossil: "#f6986b"
  nuclear: "#549ca2"
  interconnector: "#dd75b0"
  cascade: "#46caf0"
  solar: "#f9d002"
  battery: "#ace37f"
  demand_flex: "magenta"

